/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as GoogleSerpCmsImport } from './routes/google-serp-cms'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutOrdersImport } from './routes/_layout/orders'
import { Route as LayoutOffersImport } from './routes/_layout/offers'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutExploreImport } from './routes/_layout/explore'
import { Route as LayoutCustomersImport } from './routes/_layout/customers'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutSubmitFormSuccessImport } from './routes/_layout/submit-form/success'
import { Route as LayoutSubmitFormOfferImport } from './routes/_layout/submit-form/offer'
import { Route as LayoutScrapingApiUserAgentsImport } from './routes/_layout/scraping-api/user-agents'
import { Route as LayoutScrapingApiGoogleSerpImport } from './routes/_layout/scraping-api/google-serp'
import { Route as LayoutScrapingApiExploreImport } from './routes/_layout/scraping-api/explore'
import { Route as LayoutProgressJobIdImport } from './routes/_layout/progress/jobId'
import { Route as LayoutScrapingApiScrapingJobsIndexImport } from './routes/_layout/scraping-api/scraping-jobs/index'
import { Route as LayoutSupplierOfferFileIdImport } from './routes/_layout/supplier/offer/$fileId'
import { Route as LayoutScrapingApiScrapingJobsJobIdImport } from './routes/_layout/scraping-api/scraping-jobs/$jobId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const GoogleSerpCmsRoute = GoogleSerpCmsImport.update({
  id: '/google-serp-cms',
  path: '/google-serp-cms',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOrdersRoute = LayoutOrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOffersRoute = LayoutOffersImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutExploreRoute = LayoutExploreImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCustomersRoute = LayoutCustomersImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSubmitFormSuccessRoute = LayoutSubmitFormSuccessImport.update({
  id: '/submit-form/success',
  path: '/submit-form/success',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSubmitFormOfferRoute = LayoutSubmitFormOfferImport.update({
  id: '/submit-form/offer',
  path: '/submit-form/offer',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutScrapingApiUserAgentsRoute =
  LayoutScrapingApiUserAgentsImport.update({
    id: '/scraping-api/user-agents',
    path: '/scraping-api/user-agents',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutScrapingApiGoogleSerpRoute =
  LayoutScrapingApiGoogleSerpImport.update({
    id: '/scraping-api/google-serp',
    path: '/scraping-api/google-serp',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutScrapingApiExploreRoute = LayoutScrapingApiExploreImport.update({
  id: '/scraping-api/explore',
  path: '/scraping-api/explore',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProgressJobIdRoute = LayoutProgressJobIdImport.update({
  id: '/progress/jobId',
  path: '/progress/jobId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutScrapingApiScrapingJobsIndexRoute =
  LayoutScrapingApiScrapingJobsIndexImport.update({
    id: '/scraping-api/scraping-jobs/',
    path: '/scraping-api/scraping-jobs/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutSupplierOfferFileIdRoute = LayoutSupplierOfferFileIdImport.update({
  id: '/supplier/offer/$fileId',
  path: '/supplier/offer/$fileId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutScrapingApiScrapingJobsJobIdRoute =
  LayoutScrapingApiScrapingJobsJobIdImport.update({
    id: '/scraping-api/scraping-jobs/$jobId',
    path: '/scraping-api/scraping-jobs/$jobId',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/google-serp-cms': {
      id: '/google-serp-cms'
      path: '/google-serp-cms'
      fullPath: '/google-serp-cms'
      preLoaderRoute: typeof GoogleSerpCmsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/customers': {
      id: '/_layout/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof LayoutCustomersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/explore': {
      id: '/_layout/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof LayoutExploreImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/offers': {
      id: '/_layout/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof LayoutOffersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/orders': {
      id: '/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/progress/jobId': {
      id: '/_layout/progress/jobId'
      path: '/progress/jobId'
      fullPath: '/progress/jobId'
      preLoaderRoute: typeof LayoutProgressJobIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scraping-api/explore': {
      id: '/_layout/scraping-api/explore'
      path: '/scraping-api/explore'
      fullPath: '/scraping-api/explore'
      preLoaderRoute: typeof LayoutScrapingApiExploreImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scraping-api/google-serp': {
      id: '/_layout/scraping-api/google-serp'
      path: '/scraping-api/google-serp'
      fullPath: '/scraping-api/google-serp'
      preLoaderRoute: typeof LayoutScrapingApiGoogleSerpImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scraping-api/user-agents': {
      id: '/_layout/scraping-api/user-agents'
      path: '/scraping-api/user-agents'
      fullPath: '/scraping-api/user-agents'
      preLoaderRoute: typeof LayoutScrapingApiUserAgentsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/submit-form/offer': {
      id: '/_layout/submit-form/offer'
      path: '/submit-form/offer'
      fullPath: '/submit-form/offer'
      preLoaderRoute: typeof LayoutSubmitFormOfferImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/submit-form/success': {
      id: '/_layout/submit-form/success'
      path: '/submit-form/success'
      fullPath: '/submit-form/success'
      preLoaderRoute: typeof LayoutSubmitFormSuccessImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scraping-api/scraping-jobs/$jobId': {
      id: '/_layout/scraping-api/scraping-jobs/$jobId'
      path: '/scraping-api/scraping-jobs/$jobId'
      fullPath: '/scraping-api/scraping-jobs/$jobId'
      preLoaderRoute: typeof LayoutScrapingApiScrapingJobsJobIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/supplier/offer/$fileId': {
      id: '/_layout/supplier/offer/$fileId'
      path: '/supplier/offer/$fileId'
      fullPath: '/supplier/offer/$fileId'
      preLoaderRoute: typeof LayoutSupplierOfferFileIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scraping-api/scraping-jobs/': {
      id: '/_layout/scraping-api/scraping-jobs/'
      path: '/scraping-api/scraping-jobs'
      fullPath: '/scraping-api/scraping-jobs'
      preLoaderRoute: typeof LayoutScrapingApiScrapingJobsIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCustomersRoute: typeof LayoutCustomersRoute
  LayoutExploreRoute: typeof LayoutExploreRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutOffersRoute: typeof LayoutOffersRoute
  LayoutOrdersRoute: typeof LayoutOrdersRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProgressJobIdRoute: typeof LayoutProgressJobIdRoute
  LayoutScrapingApiExploreRoute: typeof LayoutScrapingApiExploreRoute
  LayoutScrapingApiGoogleSerpRoute: typeof LayoutScrapingApiGoogleSerpRoute
  LayoutScrapingApiUserAgentsRoute: typeof LayoutScrapingApiUserAgentsRoute
  LayoutSubmitFormOfferRoute: typeof LayoutSubmitFormOfferRoute
  LayoutSubmitFormSuccessRoute: typeof LayoutSubmitFormSuccessRoute
  LayoutScrapingApiScrapingJobsJobIdRoute: typeof LayoutScrapingApiScrapingJobsJobIdRoute
  LayoutSupplierOfferFileIdRoute: typeof LayoutSupplierOfferFileIdRoute
  LayoutScrapingApiScrapingJobsIndexRoute: typeof LayoutScrapingApiScrapingJobsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCustomersRoute: LayoutCustomersRoute,
  LayoutExploreRoute: LayoutExploreRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutOffersRoute: LayoutOffersRoute,
  LayoutOrdersRoute: LayoutOrdersRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProgressJobIdRoute: LayoutProgressJobIdRoute,
  LayoutScrapingApiExploreRoute: LayoutScrapingApiExploreRoute,
  LayoutScrapingApiGoogleSerpRoute: LayoutScrapingApiGoogleSerpRoute,
  LayoutScrapingApiUserAgentsRoute: LayoutScrapingApiUserAgentsRoute,
  LayoutSubmitFormOfferRoute: LayoutSubmitFormOfferRoute,
  LayoutSubmitFormSuccessRoute: LayoutSubmitFormSuccessRoute,
  LayoutScrapingApiScrapingJobsJobIdRoute:
    LayoutScrapingApiScrapingJobsJobIdRoute,
  LayoutSupplierOfferFileIdRoute: LayoutSupplierOfferFileIdRoute,
  LayoutScrapingApiScrapingJobsIndexRoute:
    LayoutScrapingApiScrapingJobsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/google-serp-cms': typeof GoogleSerpCmsRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/customers': typeof LayoutCustomersRoute
  '/explore': typeof LayoutExploreRoute
  '/items': typeof LayoutItemsRoute
  '/offers': typeof LayoutOffersRoute
  '/orders': typeof LayoutOrdersRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/progress/jobId': typeof LayoutProgressJobIdRoute
  '/scraping-api/explore': typeof LayoutScrapingApiExploreRoute
  '/scraping-api/google-serp': typeof LayoutScrapingApiGoogleSerpRoute
  '/scraping-api/user-agents': typeof LayoutScrapingApiUserAgentsRoute
  '/submit-form/offer': typeof LayoutSubmitFormOfferRoute
  '/submit-form/success': typeof LayoutSubmitFormSuccessRoute
  '/scraping-api/scraping-jobs/$jobId': typeof LayoutScrapingApiScrapingJobsJobIdRoute
  '/supplier/offer/$fileId': typeof LayoutSupplierOfferFileIdRoute
  '/scraping-api/scraping-jobs': typeof LayoutScrapingApiScrapingJobsIndexRoute
}

export interface FileRoutesByTo {
  '/google-serp-cms': typeof GoogleSerpCmsRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/customers': typeof LayoutCustomersRoute
  '/explore': typeof LayoutExploreRoute
  '/items': typeof LayoutItemsRoute
  '/offers': typeof LayoutOffersRoute
  '/orders': typeof LayoutOrdersRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/progress/jobId': typeof LayoutProgressJobIdRoute
  '/scraping-api/explore': typeof LayoutScrapingApiExploreRoute
  '/scraping-api/google-serp': typeof LayoutScrapingApiGoogleSerpRoute
  '/scraping-api/user-agents': typeof LayoutScrapingApiUserAgentsRoute
  '/submit-form/offer': typeof LayoutSubmitFormOfferRoute
  '/submit-form/success': typeof LayoutSubmitFormSuccessRoute
  '/scraping-api/scraping-jobs/$jobId': typeof LayoutScrapingApiScrapingJobsJobIdRoute
  '/supplier/offer/$fileId': typeof LayoutSupplierOfferFileIdRoute
  '/scraping-api/scraping-jobs': typeof LayoutScrapingApiScrapingJobsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/google-serp-cms': typeof GoogleSerpCmsRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/customers': typeof LayoutCustomersRoute
  '/_layout/explore': typeof LayoutExploreRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/offers': typeof LayoutOffersRoute
  '/_layout/orders': typeof LayoutOrdersRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/progress/jobId': typeof LayoutProgressJobIdRoute
  '/_layout/scraping-api/explore': typeof LayoutScrapingApiExploreRoute
  '/_layout/scraping-api/google-serp': typeof LayoutScrapingApiGoogleSerpRoute
  '/_layout/scraping-api/user-agents': typeof LayoutScrapingApiUserAgentsRoute
  '/_layout/submit-form/offer': typeof LayoutSubmitFormOfferRoute
  '/_layout/submit-form/success': typeof LayoutSubmitFormSuccessRoute
  '/_layout/scraping-api/scraping-jobs/$jobId': typeof LayoutScrapingApiScrapingJobsJobIdRoute
  '/_layout/supplier/offer/$fileId': typeof LayoutSupplierOfferFileIdRoute
  '/_layout/scraping-api/scraping-jobs/': typeof LayoutScrapingApiScrapingJobsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/google-serp-cms'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/customers'
    | '/explore'
    | '/items'
    | '/offers'
    | '/orders'
    | '/settings'
    | '/'
    | '/progress/jobId'
    | '/scraping-api/explore'
    | '/scraping-api/google-serp'
    | '/scraping-api/user-agents'
    | '/submit-form/offer'
    | '/submit-form/success'
    | '/scraping-api/scraping-jobs/$jobId'
    | '/supplier/offer/$fileId'
    | '/scraping-api/scraping-jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/google-serp-cms'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/customers'
    | '/explore'
    | '/items'
    | '/offers'
    | '/orders'
    | '/settings'
    | '/'
    | '/progress/jobId'
    | '/scraping-api/explore'
    | '/scraping-api/google-serp'
    | '/scraping-api/user-agents'
    | '/submit-form/offer'
    | '/submit-form/success'
    | '/scraping-api/scraping-jobs/$jobId'
    | '/supplier/offer/$fileId'
    | '/scraping-api/scraping-jobs'
  id:
    | '__root__'
    | '/_layout'
    | '/google-serp-cms'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/customers'
    | '/_layout/explore'
    | '/_layout/items'
    | '/_layout/offers'
    | '/_layout/orders'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/progress/jobId'
    | '/_layout/scraping-api/explore'
    | '/_layout/scraping-api/google-serp'
    | '/_layout/scraping-api/user-agents'
    | '/_layout/submit-form/offer'
    | '/_layout/submit-form/success'
    | '/_layout/scraping-api/scraping-jobs/$jobId'
    | '/_layout/supplier/offer/$fileId'
    | '/_layout/scraping-api/scraping-jobs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  GoogleSerpCmsRoute: typeof GoogleSerpCmsRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  GoogleSerpCmsRoute: GoogleSerpCmsRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/google-serp-cms",
        "/login",
        "/recover-password",
        "/reset-password",
        "/signup"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/admin",
        "/_layout/customers",
        "/_layout/explore",
        "/_layout/items",
        "/_layout/offers",
        "/_layout/orders",
        "/_layout/settings",
        "/_layout/",
        "/_layout/progress/jobId",
        "/_layout/scraping-api/explore",
        "/_layout/scraping-api/google-serp",
        "/_layout/scraping-api/user-agents",
        "/_layout/submit-form/offer",
        "/_layout/submit-form/success",
        "/_layout/scraping-api/scraping-jobs/$jobId",
        "/_layout/supplier/offer/$fileId",
        "/_layout/scraping-api/scraping-jobs/"
      ]
    },
    "/google-serp-cms": {
      "filePath": "google-serp-cms.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/recover-password": {
      "filePath": "recover-password.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_layout/admin": {
      "filePath": "_layout/admin.tsx",
      "parent": "/_layout"
    },
    "/_layout/customers": {
      "filePath": "_layout/customers.tsx",
      "parent": "/_layout"
    },
    "/_layout/explore": {
      "filePath": "_layout/explore.tsx",
      "parent": "/_layout"
    },
    "/_layout/items": {
      "filePath": "_layout/items.tsx",
      "parent": "/_layout"
    },
    "/_layout/offers": {
      "filePath": "_layout/offers.tsx",
      "parent": "/_layout"
    },
    "/_layout/orders": {
      "filePath": "_layout/orders.tsx",
      "parent": "/_layout"
    },
    "/_layout/settings": {
      "filePath": "_layout/settings.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/progress/jobId": {
      "filePath": "_layout/progress/jobId.tsx",
      "parent": "/_layout"
    },
    "/_layout/scraping-api/explore": {
      "filePath": "_layout/scraping-api/explore.tsx",
      "parent": "/_layout"
    },
    "/_layout/scraping-api/google-serp": {
      "filePath": "_layout/scraping-api/google-serp.tsx",
      "parent": "/_layout"
    },
    "/_layout/scraping-api/user-agents": {
      "filePath": "_layout/scraping-api/user-agents.tsx",
      "parent": "/_layout"
    },
    "/_layout/submit-form/offer": {
      "filePath": "_layout/submit-form/offer.tsx",
      "parent": "/_layout"
    },
    "/_layout/submit-form/success": {
      "filePath": "_layout/submit-form/success.tsx",
      "parent": "/_layout"
    },
    "/_layout/scraping-api/scraping-jobs/$jobId": {
      "filePath": "_layout/scraping-api/scraping-jobs/$jobId.tsx",
      "parent": "/_layout"
    },
    "/_layout/supplier/offer/$fileId": {
      "filePath": "_layout/supplier/offer/$fileId.tsx",
      "parent": "/_layout"
    },
    "/_layout/scraping-api/scraping-jobs/": {
      "filePath": "_layout/scraping-api/scraping-jobs/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
